//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyFavorites
    {
        public int PersonId { get; set; }
        public int ShowId { get; set; }
        public string Style { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
