//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> Svt1 { get; set; }
        public Nullable<bool> Svt2 { get; set; }
        public Nullable<bool> Tv3 { get; set; }
        public Nullable<bool> Tv4 { get; set; }
        public Nullable<bool> Kanal5 { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
