//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DagensTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularContent
    {
        public int Id { get; set; }
        public string ImgUrl { get; set; }
        public string ImgTitle { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ChannelId { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
